name: 'CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn lint

      - name: Run prettier
        run: yarn format

      - name: Run tests
        run: yarn test

      - name: Publish to Chromatic
        uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
