name: 'CI'

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  app-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Run Eslint
        run: yarn lint

      - name: Run Prettier
        run: yarn format

      - name: Run Tests
        run: yarn test

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
